### ISSUE TITLE
Investigate four-membered ring parameters

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/smirnoff99Frosst#10]
In AlkEthOH and elsewhere, parm99, parm@Frosst and smirff99Frosst differ from GAFF and GAFF2 in terms of the geometry of cyclobutane rings; the first three make these rings essentially planar, whereas GAFF and GAFF2 make them puckered (which is probably more correct).

The difference seems to be a result of the specific four-membered-ring Sp3 carbon parameters in GAFFn, i.e. for `cy-cy-cy`. A similar pucker could be added here via something like this

``` XML
<Angle smirks="[#6X4r4:1]~;@[#6X4r4:2]~;@[#6X4r4:3]" angle="88.4" k="89.66" id="a7b"/> <!-- cy-cy-cy GAFF angle -->
```

which would basically be a direct port of the GAFF parameters.

However, rather than doing that, we probably ought to investigate what the parameters ought to be. 

( @cbayly13 might be interested in this.)

**Comment by bannanc** [comment]
I believe this is the same issue we discussed in #65. We added cyclobutyl angle parameters in #66 so I'm going to close this issue. 
One note that Christopher made when discussing these parameters is its possible if there was anharmonicity introduced in the functional form for the angle parameters it is possible the extra ring parameters would not be necessary.
