### ISSUE TITLE
t47 barrier height possibly too small

### ISSUE THREAD

**Issue by diogomart** [openforcefield/smirnoff99Frosst#105]
Hello,

I seems that the barrier height `k1=0.25` of [t47](https://github.com/openforcefield/smirnoff99Frosst/blob/48933e268d4f7d4372b64727d94c6a796114f680/smirnoff99frosst/offxml/smirnoff99Frosst-1.1.0.offxml#L187) (`"[*:1]~[#6X3:2]-[#6X3$(*=[#8,#16,#7]):3]~[*:4]"`) should be larger, perhaps by a factor of 3 or 4.

For comparison, [t43](https://github.com/openforcefield/smirnoff99Frosst/blob/48933e268d4f7d4372b64727d94c6a796114f680/smirnoff99frosst/offxml/smirnoff99Frosst-1.1.0.offxml#L183) (`"[*:1]~[#6X3:2]-[#6X3:3]~[*:4]"`) has `k1=0.625`.

Similar barriers in GAFF2 are:
`ca-ca-c -o   PK=0.5225`
`ca-cp-cp-ca PK=0.795`

**Comment by j-wags** [comment]
Thanks for the thoughtful report, @diogomart. 

SMIRNOFF99Frosst is an un-optimized force field -- It was intended to give us the starting SMARTS patterns that faithfully reproduce the original parm@frosst FF, but not modify the numerical parameter values.

Our first effort at optimizing the numerical values in the FF is ["Parsley"](https://github.com/openforcefield/openforcefields#open-force-fields) (with the technical name `openff-1.0.0`). The [corresponding value for `t47`](https://github.com/openforcefield/openforcefields/blob/master/openforcefields/offxml/openff-1.0.0.offxml#L188) in Parsley did indeed increase by roughly a factor of 3.

> `<Proper smirks="[*:1]~[#6X3:2]-[#6X3$(*=[#8,#16,#7]):3]~[*:4]" periodicity1="2" phase1="180.0 * degree" k1="0.7548786939088 * mole**-1 * kilocalorie" id="t47" idivf1="1.0"></Proper>`

Replacing smirnoff99Frosst with Parsley should improve the quality of your results. For the next several years, the most recent FFs from Open Force Field will be available in that repo.

More information about our first round of fitting and benchmarking is available at https://openforcefield.org/news/introducing-openforcefield-1.0/, and we're hoping to release the next iteration later this year.

**Comment by diogomart** [comment]
Thank you for the thorough clarification @j-wags, this is really helpful.

**Comment by j-wags** [comment]
Glad to help. I'm going to mark this issue as resolved. Please let us know if you have any more feedback!
