### ISSUE TITLE
Conda install location question

### ISSUE THREAD

**Issue by bannanc** [openforcefield/smirnoff99Frosst#56]
@davidlmobley I have a question about the conda install location. I called the conda install today and then I went to look in anaconda packages at `anaconda/lib/python3.5/site-packages/` since that is where I'm used to having things installed. There are two files there:
```
.../site-packages/smirnoff99frosst-1.0.6-py3.5.egg
.../site-packages/smirnoff99frosst.pth
```
Shouldn't there also be a smirnoff99frosst/ directory with the ffxml file? the __init__.py script is currently empty is that why it isn't copying the files?

**Comment by davidlmobley** [comment]
I'm not that familiar with how things get organized within `anaconda`'s directory tree. Naively i would guess the ffxml file would be inside the egg...?

**Comment by jchodera** [comment]
Where do we want the ffxml file to be installed?

We have a few choices:
* $MINICONDA/share/smirnoff/ or some other obvious subdirectory in the miniconda insta
* A subdirectory within the installed smirnoff python package as @bannanc suggests above, which has to be looked up using a method that figures out where an imported package lives on disk

There is a mechanism to have packages register that they provide functionality for other packages. We could have smirnoff99frosst register that it provides a smirnoff ffxml directory that should be added to the default smirnoff search path. This is the same mechanism we've added to OpenMM's ForceField for the coming openmm-forcefields package.

**Comment by bannanc** [comment]
@davidlmobley 
The egg is a file note a directory, it isn't human readable so its not completely clear to me what is inside it. 
I don't have a strong preference for where it goes, but it seems bad to advertise the conda install and then not have access to the ffxml file somewhere.

**Comment by bannanc** [comment]
@nathanmlim 
mentions preserving the egg file in PR #28 So maybe you can access things from that?

**Comment by davidlmobley** [comment]
@bannanc - why don't you talk to @nathanmlim IRL and see if he knows how to deal with this in view of https://github.com/open-forcefield-group/smirnoff99Frosst/pull/29 ? 

I agree the best long-term solution will be that suggested by @jchodera : 

> There is a mechanism to have packages register that they provide functionality for other packages. We could have smirnoff99frosst register that it provides a smirnoff ffxml directory that should be added to the default smirnoff search path. This is the same mechanism we've added to OpenMM's ForceField for the coming openmm-forcefields package.

I just don't know how to do this yet and probably can't figure it out until after my travel in early June due to grant deadlines and teaching.

**Comment by jchodera** [comment]
Just to give you an idea of what needs to be done:

* `ForceField` should use [this idiom](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L50-L58) to add registered entry points to its default search path. I suggest we call our entry point `openforcefield.smirnoff.forcefields` or something that uniquely specifies that this is a directory containing SMIRNOFF forcefield files.
* `ForceField` should [search `_dataDirectories` when the file is not found](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L203-L208).
* smirnoff99Frosst should [use this mechanism in `setup.py`](http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) to register the directory containing ffxml files as `openforcefield.smirnoff.forcefields`

**Comment by jchodera** [comment]
I'm afraid I'm a bit swamped here and can't take a stab at this just yet. Does anyone else have time to take a stab at [the three things that need to be done](https://github.com/open-forcefield-group/smirnoff99Frosst/issues/56#issuecomment-304128408) in a PR?

**Comment by j-wags** [comment]
We've settled on a few standards here that are mirrored in the https://github.com/openforcefield/openforcefields repo, so I think we can call this settled. 

https://github.com/openforcefield/smirnoff99Frosst/blob/579482340173cc8ab5b79ee0ac0ab5e43ce98d29/setup.py#L40-L61
