### ISSUE TITLE
SMIRNOFF release after Spring/Summer Pull Requests

### ISSUE THREAD

**Issue by bannanc** [openforcefield/smirnoff99Frosst#60]
We've had 4 PR's since the last release 

#52 - `[#1:1]-[#6X4]~[*;+1;+2]` --> `[#1:1]-[#6X4]~[*+1,*+2]`

#57 - replace R with x (to make RDKit compatible since OpenEye toolkits treat these as the same)

#58 - Update Setup file to install everything correctly

#59 - Add monovalent ion parameters. 

@davidlmobley I know we're planning on adding HX parameters as well. Gaetano mentioned today that he is planning to compare results for FreeSolv with and without HX. I don't think any of the parameters above would affect FreeSolv molecules, but we should probably get those changes into a release.

**Comment by davidlmobley** [comment]
Yes, none of these affect FreeSolv, and are all very minor, so I haven't done a release, but is worth doing one.

The HX change would be a much more major change and is a somewhat longer-term issue (I think the thing Gaetano and I discussed doing is that I'd re-run all the hydroxyl containng compounds in FreeSolv WITH this modification after he does them without it, as validation, so I'd at least need to wait until doing that). I'm NOT going to just change the parameter on the repo and then test it; it will go the other way around -- I test it on hydration and densities and dielectric constants, etc., then I change it in the repo.

**Comment by bannanc** [comment]
> I'm NOT going to just change the parameter on the repo and then test it; it will go the other way around

I agree that is the appropriate order to make changes. 

Gaetano was asking about if he should use the 1.0.5 release or if we would have another with the more recent changes.

**Comment by davidlmobley** [comment]
The 1.0.5 release should be fine, or we could do another, but none of the changes in the interim will affect the FreeSolv calculations.

**Comment by davidlmobley** [comment]
@bannanc - can you please do a new release?

**Comment by bannanc** [comment]
yes I'll do it later today.

**Comment by bannanc** [comment]
We did this PR #70 was after the release for version 1.0.6, closing issue.
