### ISSUE TITLE
Many bonds are being assigned wildcard parameters in alpha-cyclodextrin

### ISSUE THREAD

**Issue by slochower** [openforcefield/smirnoff99Frosst#73]
I'm trying to parameterize a host molecule and keep running into many bonds being not matched at all (i.e., getting assigned the default `<Bond smirks="[*:1]~[*:2]" id="b1" k="2000.0" length="4.0"/>`). It seems to happen for this molecule with either GAFF or SYBYL atom types. The bonds that are mismatched are mostly, but not entirely, between residues.

A short example can be found at [this](https://github.com/slochower/smirnoff-host-guest/blob/3d54d0c118fab3faefe03193bee1bea5b6358256/smirnoff-bond-matching-error.ipynb) notebook. The notebook takes a few seconds to load because I printed the contents of the `mol2` and `pdb` files at the bottom. You can also get the relevant files by cloning https://github.com/slochower/smirnoff-host-guest and running `smirnoff-bond-matching-error.ipynb`. 

CC @bannanc

**Comment by davidlmobley** [comment]
The most obvious thing to check as a starting point would be to loop over the atoms and print their elements. I'd guess this is a problem with reading your OEMol... (Though it might be nice to know an example of a bond which is getting assigned this paraemter just to be sure.)

**Comment by nhenriksen** [comment]
Where did you get your SYBYL types?  (heh, from me?) They look wrong, specifically Os and Ho.
The only remaining link to the Tripos File Format PDF is down, but this site has the types:
http://www.sdsc.edu/CCMS/Packages/cambridge/pluto/atom_types.html#B

**Comment by davidlmobley** [comment]
Haha. "Os" is what OpenEye gives you if you read in a molecule with GAFF types without using the "Forcefield" flavor reader and write it back out; you tend to get certain oxygen types being interpreted as "Osmium" (Os), which inevitably results in exactly this issue. 

(We really need to add the input sanity checks in `openforcefield` to start giving more informative error messages for this type of thing.)

**Comment by slochower** [comment]
@nhenriksen I used OpenEye to assign Tripos atom types and write out a `mol2` -- so, not from you. But if OpenEye has a problem read in the initial atom types, obviously it's not going to write the correct SYBYL atom types.

@davidlmobley @bannanc Yes, osmium it is. Do you mean `OEIFlavor_MOL2_GeneralFFFormat`? I did expect that reading GAFF atom types would be trouble without using that, but I didn't expect problems with SYBYL atom types, and so I wasn't using `OEIFlavor_MOL2_GeneralFFFormat`. The piece that I overlooked is that I had previously (not in this example, but elsewhere) used OpenEye tools to write the SYBYL formatted atom types, and at that time, OpenEye had written osmium for oxygen atom types. Ignoring the SYBYL formatted `mol2` and forcing OpenEye to read the GAFF atom types with `OEIFlavor_MOL2_GeneralFFFormat` seems to fix the issue! Will further test this weekend.

Thanks, all!

**Comment by nhenriksen** [comment]
I would suggest you use antechamber to convert the original GAFF `mol2` to a SYBYL `mol2`.  I know it's adding another AMBER step, but your already starting with AMBER files, so you might as well use something that OpenEye understands.

**Comment by slochower** [comment]
@nhenriksen Yep.

**Comment by davidlmobley** [comment]
Key issue, @slochower , is that if you ever read and/or write an mol2 file with GAFF types using the OpenEye tools without using the forcefield flavor mol2 reader/writers, you'll have exactly this issue (you end up with Osmium or similar in your atom types, and there's no escaping once you have that). As long as you use the forcefield flavor anytime you interact with GAFF or non-SYBYL types (at least in my experience) it behaves, but if you ever don't do that then you end up with incorrect atom types and it's all downhill from there.

Shall I mark this as closed?

**Comment by slochower** [comment]
Yes!

FWIW, I wrote this quick little function that I'm looping into all my system preparations. Could be a useful sanity check for other people:

```python
def check_bond_lengths(structure, threshold):
    """
    Print out any equilibrium bond lengths above a certain threshold, to make sure all the assigned parameters are sensible.
    
    Parameters:
    ----------
    structure : pmd.structure
        ParmEd structure with parameters
    threshold : float
        Bond length (`R eq`)
    """
    bad_bonds = False
    for bond in structure.bonds:
        atom1, atom2 = bond.atom1, bond.atom2
        if bond.type is not None:
            if bond.type.req > threshold:
                print(f'{atom1.idx + 1:7d} {atom1.name:4} ({atom1.type:4}) {atom2.idx + 1:7d} '
                    f'{atom2.name:4} ({atom2.type:4}) {bond.type.req:10.4f} {bond.type.k:10.4f}')
                bad_bonds = True
    if not bad_bonds:
        print('Structure looks good.')

```

Also, I would suggest setting the wildcard to something worse than 4.0 Å, if that is technically possible. That value was not quite bad enough to make my simulations crash -- and I just ended up with a distorted alpha-cyclodextrin -- so I spent a chunk of time thinking the issue was mapping the MD restraints to new atom indices. If the wildcard bond length was something like 10 or 999 Å, I think the simulations would crash immediately and I might have checked the parameters more quickly. Thoughts?

**Comment by slochower** [comment]
Or, actually, rather than messing with the wildcard length, it would probably be fine to simply print out that a certain bond is matching the wildcard. That would have also gotten my attention and would be less disruptive than setting the wildcard to 999 Å.

**Comment by davidlmobley** [comment]
We're actually just going to remove the wildcard (see #72 ) so you'll get an Exception in such cases.

Sorry about that.
