### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bannanc** [openforcefield/smirnoff99Frosst#82]
The README has a note about the SMARTY classes being moved to openforcefield, but hasn't been updated since the code was removed from SMARTY. We should also cite the SMIRNOFF paper since its up. 

Anything else that has changed?

I can do this, and address issue #81.

**Comment by davidlmobley** [comment]
Sounds great. Thanks!

**Comment by bannanc** [comment]
OK, these have all been fixed as of PR #87
