### ISSUE TITLE
Should license be CC BY 4.0, rather than MIT?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/smirnoff99Frosst#88]
Since this repo does not contain code, but rather parameters (or text content), it seems like we should instead use the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/) rather than the MIT license (appropriate for code). The plaintext version of CC BY 4.0 can be found [here](https://creativecommons.org/licenses/by/4.0/legalcode.txt).

**Comment by davidlmobley** [comment]
Agree, yes.

**Comment by bannanc** [comment]
I'm adding this to my open PR #87

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
Fixed by @bannanc in #87.
