### ISSUE TITLE
Fix typo in t56

### ISSUE THREAD

**Issue by bannanc** [openforcefield/smirnoff99Frosst#89]
This SMIRKS `"[!1:1]-[#7X4,#7X3:2]-[#6X4;r3:3]-[*:4]"` should be `"[!#1:1]-[#7X4,#7X3:2]-[#6X4;r3:3]-[*:4]"`. The first means not an isotope with mass 1 (`!1`), but we want to catch all hydrogens so it should be `!#1`. This was raised on [openforcefield issue#247](https://github.com/openforcefield/openforcefield/issues/247).

**Comment by j-wags** [comment]
This issue has been resolved in PR #90.
